# 수강생 분의 이름과 학번을 입력해주세요.

In [1]:
print("주준하", "20197132")

주준하 20197132


# Getting Started with pandas, numpy, and matplotlib

In [2]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import matplotlib.pyplot as plt

# Pandas 실습

### Series

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
print(obj.values)
print(obj.index)  # like range(4)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])  # index 임의로 설정하기
obj2


d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
print(obj2['a'])
obj2['d'] = 6
print(obj2[['c', 'a', 'd']])

-5
c    3
a   -5
d    6
dtype: int64


In [8]:
print(obj2 > 0)
obj2[obj2 > 0]


d     True
b     True
a    False
c     True
dtype: bool


d    6
b    7
c    3
dtype: int64

In [9]:
print(obj2 * 2)
print(np.exp(obj2))  # exponential 함수

d    12
b    14
a   -10
c     6
dtype: int64
d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64


In [10]:
print('b' in obj2.index)
print('e' in obj2.index)

True
False


In [11]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [12]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [13]:
pd.isnull(obj4)  # null 있는지?


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [14]:
pd.notnull(obj4)  # null 없는지?

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [15]:
obj4.isnull()  # null 있는지?

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

### DataFrame

In [16]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [17]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [18]:
frame.head()  # 데이터프레임 샘플 확인

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [19]:
frame.tail()  # 데이터프레임 샘플 확인

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [20]:
frame.describe()  # 수치형 데이터에 대해 주요 통계치 출력

year       pop
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000

In [21]:
frame = frame.astype({'year': str})  # 수치형 데이터를 문자열 데이터로 타입 변경 (one-hot vector 생성을 위함)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [22]:
pd.get_dummies(frame)  # 카테고리 문자열 데이터를 one-hot vector로 변환

pop  state_Nevada  state_Ohio  year_2000  year_2001  year_2002  year_2003
0  1.5             0           1          1          0          0          0
1  1.7             0           1          0          1          0          0
2  3.6             0           1          0          0          1          0
3  2.4             1           0          0          1          0          0
4  2.9             1           0          0          0          1          0
5  3.2             1           0          0          0          0          1

In [23]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [24]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
print(frame2)
print(frame2.columns)
print(frame2.index)
# 리스트(list): 새로운 라벨 인덱싱하면 오류 발생
# 딕셔너리(dictionary): 새로운 라벨 인덱싱하면 새로운 라벨 생성

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')
Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')


In [25]:
frame2['state']  # 데이터프레임의 'state' 열의 정보(index, values) 출력

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [26]:
frame2.year  # 데이터프레임의 'year' 열의 정보 출력

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [27]:
frame2.loc['three']  # loc: location 의미, [행, 열] 순으로 라벨 인덱싱할 때 사용

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [28]:
frame2.loc['three', 'state']  # loc: location 의미, [행, 열] 순으로 라벨 인덱싱할 때 사용

'Ohio'

In [29]:
frame2['debt'] = 16.5
print(frame2)
frame2['debt'] = np.arange(6.)
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5
       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0


In [30]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [31]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [32]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [33]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [34]:
frame3 = pd.DataFrame(pop)
print(frame3.index)
frame3

Int64Index([2001, 2002, 2000], dtype='int64')


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [35]:
frame3.T  # 데이터프레임 transpose 시키기

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [36]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [37]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

# NumPy 실습

In [38]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [39]:
%time for _ in range(10): my_arr2 = my_arr * 2  # ndarray 연산 시간 측정
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]  # list 연산 시간 측정

CPU times: user 20.5 ms, sys: 5.9 ms, total: 26.4 ms
Wall time: 27.3 ms
CPU times: user 829 ms, sys: 188 ms, total: 1.02 s
Wall time: 1.02 s


## The NumPy ndarray: A Multidimensional Array Object

In [45]:
import numpy as np

# 문제 1. 표준 정규 분포(평균 0, 표준편차 1)에서 난수 ndarray 생성하기
# ndarray 이름: data
# ndarray 크기: (2, 3)

# 정답 1.
data = np.random.randn(2, 3)
data

array([[ 0.32401734,  1.67705262, -1.0136026 ],
       [-0.74168252,  0.1549708 , -0.58602789]])

In [46]:
# 문제 2. 0부터 1사이의 균일 분포에서 난수 ndarray 생성하기
# ndarray 이름: data2
# ndarray 크기: (2, 3)

# 정답 2.
data2 = np.random.rand(2, 3)
data2

array([[0.41569344, 0.57961809, 0.93998902],
       [0.14424661, 0.46473376, 0.35796689]])

In [50]:
# 문제 3. 균일 분포에서 정수 난수 1개 생성하기
# 난수 객체 이름: data3
# 난수 범위: (1, 20)

# 정답 3.
data3 = np.random.randint(1, 20)
data3

1

In [51]:
# 문제 4. data 배열에 10 곱하기

# 정답 4.
data * 10

array([[  3.24017342,  16.77052619, -10.13602599],
       [ -7.41682516,   1.54970799,  -5.86027889]])

In [52]:
# 문제 5. data 배열에 data 배열 더하기

# 정답 5.
data + data

array([[ 0.64803468,  3.35410524, -2.0272052 ],
       [-1.48336503,  0.3099416 , -1.17205578]])

In [53]:
# 문제 6. data 배열 크기 출력하기

# 정답 6.
data.shape

(2, 3)

In [54]:
# 문제 7. data 데이터타입 출력하기

# 정답 7.
type(data)

numpy.ndarray

### Creating ndarrays

In [57]:
# 문제 8. 아래 리스트를 이용하여 NumPy ndarray 생성하기
# ndarray 이름: arr1
data1 = [6, 7.5, 8, 0, 1]

# 정답 8.
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [58]:
# 문제 9. 아래 리스트를 이용하여 ndarray 생성하기
# ndarray 이름: arr2
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

# 정답 9.
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
# 문제 10. 크기 10이고 0으로 초기화한 ndarray 생성하기
# ndarray 이름: data_zero

# 정답 10.
data_zero = np.zeros((10))
data_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
# 문제 11. 크기 (3, 6)이고 0으로 초기화한 ndarray 생성하기
# ndarray 이름: data_zero1

# 정답 11.
data_zero1 = np.zeros((3, 6))
data_zero1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [63]:
# 문제 12. 크기 (2, 3, 2)이고 초기화하지 않은 ndarray 생성하기
# ndarray 이름: data_empty

# 정답 12.
data_empty = np.empty((2, 3, 2))
data_empty

array([[[5., 0.],
        [5., 0.],
        [7., 0.]],

       [[4., 0.],
        [5., 0.],
        [8., 0.]]])

In [64]:
# 문제 13. 0 부터 15 전까지 시퀀스 배열 생성하기

# 정답 13.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
# 문제 14. 0 부터 2 전까지 스텝크기 0.1 인 시퀀스 배열 생성하기

# 정답 14.
np.arange(0, 2, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

### Data Types for ndarrays

In [67]:
# 문제 15. 아래의 리스트를 이용하여 데이터타입이 np.float64인 ndarray 생성하기
# ndarray 이름: arr1
data_list = [1, 2, 3]

# 정답 15.
arr1 = np.array(data_list, dtype=np.float64)
print(arr1, arr1.dtype)

[1. 2. 3.] float64


In [68]:
# 문제 16. 아래의 리스트를 이용하여 데이터타입이 np.int32인 ndarray 생성하기
# ndarray 이름: arr2
data_list = [1, 2, 3, 4, 5]

# 정답 16.
arr2 = np.array(data_list, dtype=np.int32)
print(arr2, arr1.dtype)

[1 2 3 4 5] float64


In [71]:
# 문제 17. 문제 16에서 생성한 arr2의 데이터타입을 np.float64 로 변환한 ndarray의 데이터타입 출력하기
# ndarray 이름: float_arr

# 정답 17.
arr2 = arr2.astype(np.float64)
print(arr2, arr2.dtype)

[1. 2. 3. 4. 5.] float64


In [72]:
# 문제 18. 아래의 ndarray를 np.int32 로 변환한 ndarray 생성하기
# ndarray 이름: int_arr
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

# 정답 18.
int_arr = np.array(arr, dtype=np.int32)
print(int_arr, int_arr.dtype)

[ 3 -1 -2  0 12 10] int32


In [73]:
# 문제 19. 아래의 ndarray를 np.float64로 변환한 ndarray 생성하기
# ndarray 이름: float_arr
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

# 정답 19.
float_arr = numeric_strings.astype(np.float64)
print(float_arr, float_arr.dtype)

[ 1.25 -9.6  42.  ] float64


### Arithmetic with NumPy Arrays

In [75]:
# 문제 20. 아래 2개의 ndarray 간의 element-wise 곱하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[4., 5., 6.], [1., 2., 3.]])

# 정답 20.
arr1 * arr2

array([[ 4., 10., 18.],
       [ 4., 10., 18.]])

In [76]:
# 문제 21. 아래 2개의 ndarray 간의 element-wise 나누기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[4., 5., 6.], [1., 2., 3.]])

# 정답 21.
arr1 / arr2

array([[0.25, 0.4 , 0.5 ],
       [4.  , 2.5 , 2.  ]])

In [77]:
# 문제 22. 아래 ndarray에 element-wise 0.5 거듭제곱하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

# 정답 22.
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [78]:
# 문제 23. 아래 ndarray을 transpose하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

# 정답 23.
np.transpose(arr1)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [79]:
# 문제 24. 아래 2개의 ndarray을 행렬 곱하여 arr3 생성하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = arr1.T

# 정답 24.
arr3 = np.matmul(arr1, arr2)
arr3

array([[14., 32.],
       [32., 77.]])

In [80]:
# 문제 25. arr1이 3.5보다 큰지에 대해 불린 배열 출력하기
arr1 = np.array([1., 2., 3., 4., 5., 6.])

# 정답 25.
arr1 > 3.5

array([False, False, False,  True,  True,  True])

In [81]:
# 문제 26. arr1이 3.5보다 큰 배열 인덱스 출력하기
arr1 = np.array([1., 2., 3., 4., 5., 6.])

# 정답 26.
np.where(arr1 > 3.5)

(array([3, 4, 5]),)

In [83]:
# 문제 27. arr2중에서 가장 큰 값 출력하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 27.
np.amax(arr2)

6.0

In [84]:
# 문제 28. arr2중에서 가장 큰 값 인덱스 출력하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 28.
np.argmax(arr2)

2

In [85]:
# 문제 29. arr2 오름차순으로 정렬하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 29.
np.sort(arr2)

array([1., 2., 3., 4., 5., 6.])

In [86]:
# 문제 30. arr2 오름차순으로 정렬했을 때의 인덱스 출력하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 30.
np.argsort(arr2)

array([3, 4, 5, 0, 1, 2])

### Basic Indexing and Slicing

In [88]:
# 문제 31. 아래 arr 배열 인덱스 5부터 8전까지의 값을 12로 변경하기 
arr = np.arange(10)

# 정답 31.
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [94]:
# 문제 32. 문제 29의 arr 배열의 인덱스 5부터 8전까지를 슬라이싱하여 arr_slice 배열 생성하기

# 정답 32.
arr_slice = arr[5:8]
arr_slice

array([   12, 12345,    12])

In [95]:
# 문제 33. 문제 30의 arr_slice의 인덱스 1번째 값을 12345로 변경하고 arr 배열 출력하기
# arr 배열의 값이 왜 변경되었을까 생각해보기

# 정답 33.
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [96]:
# 문제 34. 문제 31의 arr_slice 배열의 모든 값을 64로 변경하고 arr 배열 출력하기

# 정답 34.
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [99]:
# 문제 35. 문제 31의 arr_slice 배열의 복사본을 생성하고 모든 값을 9999로 변경하고 arr 배열 출력하기

# 정답 35.
arr_slice = arr_slice.copy()
arr_slice[:] = 9999
print(arr)
print(arr_slice)

[ 0  1  2  3  4 64 64 64  8  9]
[9999 9999 9999]
